version: "3"
services:
  user:
    build:
      context: .
      dockerfile: docker/user/Dockerfile
    env_file:
      - .env
    network_mode: "host"
  reading:
    build:
      context: .
      dockerfile: docker/reading/Dockerfile
    env_file:
      - .env
    network_mode: "host"
  catalog:
    build:
      context: .
      dockerfile: docker/catalog/Dockerfile
    env_file:
      - .env
    network_mode: "host"
  static:
    build:
      context: .
      dockerfile: docker/static/Dockerfile
    env_file:
      - .env
    network_mode: "host"
  profile:
    build:
      context: .
      dockerfile: docker/profile/Dockerfile
    env_file:
      - .env
    network_mode: "host"
  activity:
    build:
      context: .
      dockerfile: docker/activity/Dockerfile
    env_file:
      - .env
    network_mode: "host"
  gateway:
    build:
      context: .
      dockerfile: docker/gateway/Dockerfile
    env_file:
      - .env
    network_mode: "host"
    depends_on:
      - activity
      - user
      - reading
      - catalog
      - static
  client:
    build:
      context: micromango-client/
      dockerfile: Dockerfile
    environment:
      - NEXT_PUBLIC_SERVER_ADDR=http://127.0.0.1:8080
    network_mode: "host"
