version: "3"
services:
  user:
    build:
      context: .
      dockerfile: docker/user/Dockerfile
    env_file:
      - .env
    network_mode: "host"
  reading:
    build:
      context: .
      dockerfile: docker/reading/Dockerfile
    env_file:
      - .env
    network_mode: "host"
  catalog:
    build:
      context: .
      dockerfile: docker/catalog/Dockerfile
    env_file:
      - .env
    network_mode: "host"
  static:
    build:
      context: .
      dockerfile: docker/static/Dockerfile
    env_file:
      - .env
    network_mode: "host"
  gateway:
    build:
      context: .
      dockerfile: docker/gateway/Dockerfile
    env_file:
      - .env
    network_mode: "host"
    depends_on:
      - user
      - reading
      - catalog
      - static
