apiVersion: apps/v1
kind: Deployment
metadata:
  name: micromango-gateway-dep
  labels:
    app: micromango-app
spec:
  selector:
    matchLabels:
      app: micromango-app
  template:
    metadata:
      labels:
        app: micromango-app
    spec:
      containers:
        - name: gateway-app
          image: micromango-gateway:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: micromango-settings
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: micromango-client-dep
  labels:
    app: micromango-app
spec:
  selector:
    matchLabels:
      app: micromango-app
  template:
    metadata:
      labels:
        app: micromango-app
    spec:
      containers:
        - name: client-app
          image: micromango-client
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: micromango-settings
---
# First, add the Service API
apiVersion: v1
# This will be the Service setup
kind: Service
metadata:
  # Your service name
  name: micromango-src
spec:
  selector:
    # selector that matches the pod
    app: micromango-app
  # type of service
  type: LoadBalancer
  ports:
    - protocol: TCP
      # port for exposing the service
      port: 8080
      # port for exposing the pod
      targetPort: gateway-app
      # port for exposing the node
      nodePort: 31110
      name: api
    - protocol: TCP
      port: 3000
      targetPort: client-app
      nodePort: 31111
      name: client
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: micromango-settings
data:
  USER_ADDR: ":50001"
  USER_DB_ADDR: "user.sqlite"
  USER_SALT: "qwerty"
  USER_JWT_SECRET: "to_generate_later"
  CATALOG_ADDR: ":50002"
  CATALOG_DB_ADDR: "catalog.sqlite"
  READING_ADDR: ":50003"
  READING_DB_ADDR: "reading.sqlite"
  STATIC_ADDR: ":50004"
  GATEWAY_ADDR: ":8080"
  SERVER_ADDR: "http://10.102.218.234:8080"
  PROFILE_ADDR: ":50005"
  PROFILE_DB_ADDR: "profile.sqlite"
  ACTIVITY_ADDR: ":50006"
  ACTIVITY_DB_ADDR: "activity.sqlite"
  NEXT_PUBLIC_SERVER_ADDR: "http://10.102.218.234:8080"