apiVersion: apps/v1
kind: Deployment
metadata:
  name: micromango-gateway-dep
  labels:
    app: micromango-app
    service: gateway-service
    tier: api
spec:
  selector:
    matchLabels:
      app: micromango-app
      service: gateway-service
      tier: api
  template:
    metadata:
      labels:
        app: micromango-app
        service: gateway-service
        tier: api
    spec:
      containers:
        - name: gateway-app
          image: micromango-gateway:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
              name: gateway-port
          envFrom:
            - configMapRef:
                name: micromango-settings
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: micromango-client-dep
  labels:
    app: micromango-app
    service: client-service
    tier: api
spec:
  selector:
    matchLabels:
      app: micromango-app
      service: client-service
      tier: api
  template:
    metadata:
      labels:
        app: micromango-app
        service: client-service
        tier: api
    spec:
      containers:
        - name: client-app
          image: micromango-client
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_SERVER_ADDR
              value: "http://127.0.0.1:8080"
            - name: SERVER_ADDR
              value: "http://micromango-src:8080"
          envFrom:
            - configMapRef:
                name: micromango-settings
---
# First, add the Service API
apiVersion: v1
# This will be the Service setup
kind: Service
metadata:
  # Your service name
  name: micromango-src
  labels:
    app: micromango-app
    tier: api
spec:
  selector:
    app: micromango-app
    tier: api
  # type of service
  type: LoadBalancer
  ports:
    - protocol: TCP
      # port for exposing the service
      port: 8080
      targetPort: 8080
      name: api
    - protocol: TCP
      port: 3000
      targetPort: 3000
      name: client
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: micromango-settings
data:
  USER_ADDR: "user-service:50001"
  USER_DB_ADDR: "user.sqlite"
  USER_SALT: "qwerty"
  USER_JWT_SECRET: "to_generate_later"
  CATALOG_ADDR: "catalog-service:50002"
  CATALOG_DB_ADDR: "catalog.sqlite"
  READING_ADDR: "reading-service:50003"
  READING_DB_ADDR: "reading.sqlite"
  STATIC_ADDR: "static-service:50004"
  GATEWAY_ADDR: ":8080"
  SERVER_ADDR: "http://10.102.218.234:8080"
  PROFILE_ADDR: "profile-service:50005"
  PROFILE_DB_ADDR: "profile.sqlite"
  ACTIVITY_ADDR: "activity-service:50006"
  ACTIVITY_DB_ADDR: "activity.sqlite"
  NEXT_PUBLIC_SERVER_ADDR: "http://127.0.0.1:8080"